//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trab_4_Bim
{
    using System;
    using System.Collections.Generic;
    
    public partial class despesa
    {
        public int codigo { get; set; }
        public string descr { get; set; }
        public string tipo { get; set; }
        public double valor { get; set; }
        public Nullable<System.DateTime> dia { get; set; }
    }
}
